### ISSUE TITLE
{"error":"An error while decoding token."}

### ISSUE THREAD

**Issue by BoniWPy** [dedihartono/testbinar#2]
hai, gw nyoba pake, trus gw udah create user ...
trus gw login, trus gw save token nya...
pas gw mau get -> testbinard.herokuapp.com/v1/products pake parameter token yang gw dapate pas login, malah {"error":"An error while decoding token."}
kenapa ya?

**Comment by dedihartono** [comment]
![image](https://user-images.githubusercontent.com/16358944/64315305-db90d400-cfdb-11e9-8491-5e91d12ce162.png)

silakan coba lagi,
Headernya dipastiin pake key:Authorization

**Comment by BoniWPy** [comment]
wah betul kang...hehe..masntap..makasih...solved
